/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author rodolfo
 */
public class FrmCrearFotoEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form FrmCrearFotoEmpresa
     */
    public FrmCrearFotoEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtPaisOrigen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        txtDireccionFoto = new javax.swing.JTextField();
        txtBlog = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnOpenFile = new javax.swing.JButton();
        btnCrateImage = new javax.swing.JButton();
        txtNombreEmpresa = new javax.swing.JTextField();
        txtTwitter = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(620, 445));
        setMinimumSize(new java.awt.Dimension(620, 445));
        setPreferredSize(new java.awt.Dimension(620, 445));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel4.setText("Evento Empresarial");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 10, 200, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Fotografía");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 90, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("País de origen");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 130, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Descripción");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 80, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nombre Empresa");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 280, 110, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Facebook / Blog");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 320, 99, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Twitter");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 360, 90, 15);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 170, 330, 96);
        getContentPane().add(txtPaisOrigen);
        txtPaisOrigen.setBounds(150, 130, 190, 20);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/notImage.png"))); // NOI18N
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(350, 10, 150, 140);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/exitPrincipal.png"))); // NOI18N
        btnExit.setToolTipText("Salir");
        getContentPane().add(btnExit);
        btnExit.setBounds(540, 300, 55, 40);

        txtDireccionFoto.setEditable(false);
        getContentPane().add(txtDireccionFoto);
        txtDireccionFoto.setBounds(150, 90, 190, 20);
        getContentPane().add(txtBlog);
        txtBlog.setBounds(150, 320, 190, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mail_delete.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(350, 320, 16, 16);

        btnOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/openImage.png"))); // NOI18N
        btnOpenFile.setToolTipText("Cargar imagen");
        getContentPane().add(btnOpenFile);
        btnOpenFile.setBounds(540, 90, 55, 30);

        btnCrateImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/saveImage.png"))); // NOI18N
        btnCrateImage.setToolTipText("Crear imagen");
        getContentPane().add(btnCrateImage);
        btnCrateImage.setBounds(540, 350, 55, 40);
        getContentPane().add(txtNombreEmpresa);
        txtNombreEmpresa.setBounds(150, 280, 190, 20);
        getContentPane().add(txtTwitter);
        txtTwitter.setBounds(150, 360, 190, 20);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mail_delete.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(350, 360, 16, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eventoEmpresarial.jpg"))); // NOI18N
        jLabel3.setText("       ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 530, 404);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCrearFotoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCrearFotoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCrearFotoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCrearFotoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrearFotoEmpresa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrateImage;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBlog;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDireccionFoto;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtPaisOrigen;
    private javax.swing.JTextField txtTwitter;
    // End of variables declaration//GEN-END:variables
}
