/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author rodolfo
 */
public class FrmCrearFotoSocial extends javax.swing.JFrame {

    /**
     * Creates new form FrmCrearFotoSocial
     */
    public FrmCrearFotoSocial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtPaisOrigen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        txtDireccionFoto = new javax.swing.JTextField();
        txtPersonas = new javax.swing.JTextField();
        cbxTipoEvento = new javax.swing.JComboBox();
        btnTagPeople = new javax.swing.JButton();
        btnCrateImage = new javax.swing.JButton();
        cbxAmbiente = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        btnOpenFile = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cbxAcceso = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 520));
        setMinimumSize(new java.awt.Dimension(550, 520));
        setPreferredSize(new java.awt.Dimension(550, 520));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("Evento Social");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 10, 200, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Fotografía");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 90, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("País de origen");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 130, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 0));
        jLabel6.setText("Descripción");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 80, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 0));
        jLabel7.setText("Tipo de evento");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 280, 100, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("Etiquetar");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 320, 57, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 0));
        jLabel9.setText("Ambiente");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 360, 90, 15);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 170, 330, 96);
        getContentPane().add(txtPaisOrigen);
        txtPaisOrigen.setBounds(120, 130, 190, 20);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/notImage.png"))); // NOI18N
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(320, 10, 130, 140);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/exitPrincipal.png"))); // NOI18N
        btnExit.setToolTipText("Salir");
        getContentPane().add(btnExit);
        btnExit.setBounds(470, 390, 55, 40);

        txtDireccionFoto.setEditable(false);
        getContentPane().add(txtDireccionFoto);
        txtDireccionFoto.setBounds(120, 90, 190, 20);

        txtPersonas.setEditable(false);
        getContentPane().add(txtPersonas);
        txtPersonas.setBounds(120, 320, 190, 20);

        cbxTipoEvento.setMaximumRowCount(9);
        cbxTipoEvento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cumpleaños", "Paseo", "Boda", "Primera comunión,", "Graduación", "Despedida", "Bienvenida", "Baby shower", "Matrimonio" }));
        getContentPane().add(cbxTipoEvento);
        cbxTipoEvento.setBounds(120, 280, 190, 20);

        btnTagPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tagPeople.png"))); // NOI18N
        btnTagPeople.setToolTipText("Cargar imagen");
        btnTagPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTagPeopleActionPerformed(evt);
            }
        });
        getContentPane().add(btnTagPeople);
        btnTagPeople.setBounds(470, 320, 57, 30);

        btnCrateImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/saveImage.png"))); // NOI18N
        btnCrateImage.setToolTipText("Crear imagen");
        getContentPane().add(btnCrateImage);
        btnCrateImage.setBounds(470, 430, 55, 40);

        cbxAmbiente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aire libre", "Dentro" }));
        getContentPane().add(cbxAmbiente);
        cbxAmbiente.setBounds(120, 360, 190, 20);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mail_delete.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(320, 320, 16, 16);

        btnOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/openImage.png"))); // NOI18N
        btnOpenFile.setToolTipText("Cargar imagen");
        getContentPane().add(btnOpenFile);
        btnOpenFile.setBounds(470, 90, 55, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 0));
        jLabel10.setText("Acceso");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 400, 90, 15);

        cbxAcceso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Público", "Priva" }));
        getContentPane().add(cbxAcceso);
        cbxAcceso.setBounds(120, 400, 190, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/socialEvento.png"))); // NOI18N
        jLabel3.setText("       ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 460, 483);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTagPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTagPeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTagPeopleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCrearFotoSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCrearFotoSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCrearFotoSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCrearFotoSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrearFotoSocial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrateImage;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnTagPeople;
    private javax.swing.JComboBox cbxAcceso;
    private javax.swing.JComboBox cbxAmbiente;
    private javax.swing.JComboBox cbxTipoEvento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDireccionFoto;
    private javax.swing.JTextField txtPaisOrigen;
    private javax.swing.JTextField txtPersonas;
    // End of variables declaration//GEN-END:variables
}
